/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gateway health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with email and password
         * @description Signs the user in on success. Rate limit 5/min per IP.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Rate limit 10/min per IP.
         */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Idempotent; succeeds even without a session.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start an OAuth sign-in */
        get: operations["startOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth redirect target
         * @description Registered with the provider; not called by app code. On failure it
         *     redirects to `/auth/login?error=<code>` instead of returning an error.
         */
        get: operations["completeOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always `202`, whether or not the email exists, so it cannot be used to
         *     discover accounts. Rate limit 3/min per IP.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password while signed in */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Also the way to check whether a session is active.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete the account and all its data
         * @description Requires a fresh session (signed in within the last 10 minutes);
         *     otherwise `403`. The account is removed immediately and the cookie
         *     cleared. Files, embeddings, scenes, conversations and the subscription
         *     are purged asynchronously.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Update profile fields */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an upload
         * @description Validates type and size and reserves storage quota.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{fileId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish an upload and start processing
         * @description Idempotent; completing an already completed upload returns the file.
         */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel an in-progress upload */
        delete: operations["abortUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's files */
        get: operations["listFiles"];
        put?: never;
        /**
         * Import a file from a URL
         * @description Supports YouTube URLs. Consumes `YOUTUBE_VIDEOS` quota.
         */
        post: operations["importFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        /**
         * Get a file
         * @description Includes a short-lived `downloadUrl`.
         */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete a file and everything derived from it */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Rename a file */
        patch: operations["updateFile"];
        trace?: never;
    };
    "/files/{fileId}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the processing pipeline again */
        post: operations["reprocessFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live updates for the signed-in user
         * @description Server-Sent Events. On every (re)connect the first event is
         *     `files.snapshot` with all files still uploading or processing, so no
         *     replay is needed. A `: ping` comment is sent every 25s. Max 5
         *     concurrent streams per user.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collections */
        get: operations["listCollections"];
        put?: never;
        /** Create a collection */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        /** Get a collection */
        get: operations["getCollection"];
        put?: never;
        post?: never;
        /** Delete a collection and its sub-collections */
        delete: operations["deleteCollection"];
        options?: never;
        head?: never;
        /** Rename, recolor or move a collection */
        patch: operations["updateCollection"];
        trace?: never;
    };
    "/collections/{collectionId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse a collection's contents
         * @description Child collections first, then files.
         */
        get: operations["listCollectionItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{collectionId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add files to a collection
         * @description Idempotent; files already in the collection are ignored.
         */
        post: operations["addCollectionFiles"];
        /**
         * Remove files from a collection
         * @description Idempotent. The files themselves are not deleted.
         */
        delete: operations["removeCollectionFiles"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic search across the caller's files
         * @description Safe and idempotent. POST rather than GET keeps query text out of URLs
         *     and access logs. Rate limit 60/min per user.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations */
        get: operations["listConversations"];
        put?: never;
        /**
         * Start a conversation
         * @description Consumes `FILE_CONVERSATIONS` quota when scoped to a file or
         *     collection, `CONVERSATIONS` otherwise. Send the first message with
         *     `POST /conversations/{conversationId}/messages`.
         */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /** Get a conversation */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        /** Delete a conversation */
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /**
         * Message history
         * @description Newest first. Follow `nextCursor` to load older messages.
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * Send a message and stream the reply
         * @description Server-Sent Events. The stream always ends with a `done` or `error`
         *     event. Errors detected before streaming starts are returned as
         *     `application/problem+json`. A retry with the same `Idempotency-Key`
         *     replays the stored reply instead of asking the model again. Rate limit
         *     20/min per user.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/greeting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personalised greeting for the chat home screen */
        get: operations["getGreeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available plans
         * @description Public. When the caller is signed in, each plan carries `comparison`
         *     against the current plan.
         */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's subscription
         * @description Every user has one; new accounts start on the free plan.
         */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/change-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move to another plan
         * @description One entry point for checkout, upgrade and downgrade:
         *     - From free to paid: returns `checkoutUrl`; the plan changes once the
         *       provider confirms payment.
         *     - To a higher paid plan: upgrades immediately, prorated.
         *     - To a lower plan: scheduled for the end of the current period.
         */
        post: operations["changePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel the paid subscription
         * @description Idempotent.
         */
        post: operations["cancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause billing
         * @description Idempotent.
         */
        post: operations["pauseSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused subscription
         * @description Idempotent.
         */
        post: operations["resumeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscription/scheduled-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo a pending downgrade or cancellation */
        delete: operations["cancelScheduledChange"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota usage and storage */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment provider callback
         * @description Server to server; exempt from the `Origin` check. The raw body and
         *     headers are forwarded to payment-service, which verifies the provider
         *     signature (`X-Signature` for Lemon Squeezy, `X-Razorpay-Signature` for
         *     Razorpay). Redeliveries of the same provider event are no-ops.
         */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Id: string;
        /**
         * @description RFC 9457 problem details plus a stable machine-readable `code`.
         *     Extension members (`errors`, `metric`, `used`, `limit`) appear only
         *     where noted.
         */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string;
            /** @enum {string} */
            code: "validation_failed" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "quota_exceeded" | "rate_limited" | "upstream_unavailable" | "upstream_timeout" | "internal";
            correlationId: string;
            /** @description Field-level details for `validation_failed`. */
            errors?: {
                field: string;
                message: string;
            }[];
            metric?: components["schemas"]["UsageMetric"];
            /** Format: int64 */
            used?: number;
            /** Format: int64 */
            limit?: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            service: string;
            /** Format: date-time */
            timestamp: string;
        };
        Password: string;
        SignUpRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: components["schemas"]["Password"];
        };
        SignInRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: components["schemas"]["Password"];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: components["schemas"]["Password"];
            /** @default true */
            revokeOtherSessions: boolean;
        };
        AuthResult: {
            user: components["schemas"]["User"];
        };
        User: {
            id: components["schemas"]["Id"];
            /** Format: email */
            email: string;
            name: string;
            username: string | null;
            /** Format: uri */
            imageUrl: string | null;
            emailVerified: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateMeRequest: {
            name?: string;
            username?: string | null;
        };
        /** @enum {string} */
        FileType: "VIDEO" | "IMAGE" | "AUDIO" | "DOCUMENT" | "YOUTUBE_VIDEO" | "OTHER";
        /** @enum {string} */
        UploadStatus: "PENDING" | "UPLOADING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** @enum {string} */
        ProcessingStatus: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "SKIPPED";
        /**
         * @description Only advances, in this order.
         * @enum {string}
         */
        ProcessingStage: "UPLOAD" | "EMBEDDING" | "SCENE_DETECTION" | "INDEXING" | "COMPLETED";
        /** @enum {string} */
        UsageMetric: "CONVERSATIONS" | "STORAGE" | "FILE_CONVERSATIONS" | "YOUTUBE_VIDEOS" | "MAX_VIDEO_LENGTH" | "MAX_AUDIO_DURATION";
        /** @enum {string} */
        PlanType: "FREE" | "BASIC" | "PRO" | "ENTERPRISE";
        /** @enum {string} */
        BillingInterval: "MONTHLY" | "YEARLY";
        /** @enum {string} */
        SubscriptionStatus: "ACTIVE" | "TRIALING" | "PAST_DUE" | "PAUSED" | "CANCELLED" | "EXPIRED";
        CreateUploadRequest: {
            fileName: string;
            /** Format: int64 */
            sizeBytes: number;
            mimeType: string;
        };
        Upload: {
            file: components["schemas"]["File"];
            /** Format: int64 */
            partSizeBytes: number;
            parts: components["schemas"]["UploadPartTarget"][];
            /**
             * Format: date-time
             * @description When the part URLs stop working.
             */
            expiresAt: string;
        };
        UploadPartTarget: {
            /** Format: int32 */
            partNumber: number;
            /**
             * Format: uri
             * @description Presigned PUT URL. Read the `ETag` response header.
             */
            url: string;
        };
        CompleteUploadRequest: {
            parts: components["schemas"]["CompletedPart"][];
        };
        CompletedPart: {
            /** Format: int32 */
            partNumber: number;
            etag: string;
        };
        ImportFileRequest: {
            /** Format: uri */
            url: string;
        };
        UpdateFileRequest: {
            name: string;
        };
        File: {
            id: components["schemas"]["Id"];
            /** @description Display name; editable. */
            name: string;
            originalName: string;
            /** Format: int64 */
            sizeBytes: number;
            mimeType: string;
            type: components["schemas"]["FileType"];
            uploadStatus: components["schemas"]["UploadStatus"];
            processingStatus: components["schemas"]["ProcessingStatus"];
            processingStage: components["schemas"]["ProcessingStage"];
            errorMessage: string | null;
            /** Format: uri */
            youtubeUrl: string | null;
            /**
             * Format: uri
             * @description Short-lived presigned URL.
             */
            thumbnailUrl: string | null;
            /**
             * Format: uri
             * @description Short-lived presigned URL. Only set by `GET /files/{fileId}`.
             */
            downloadUrl: string | null;
            /** @description Technical attributes (duration, dimensions, ...). */
            attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            uploadedAt: string | null;
            /** Format: date-time */
            processingStartedAt: string | null;
            /** Format: date-time */
            processingCompletedAt: string | null;
        };
        FilePage: {
            items: components["schemas"]["File"][];
            nextCursor: string | null;
        };
        /** @description The live-updating subset of `File`. */
        FileState: {
            id: components["schemas"]["Id"];
            name: string;
            uploadStatus: components["schemas"]["UploadStatus"];
            processingStatus: components["schemas"]["ProcessingStatus"];
            processingStage: components["schemas"]["ProcessingStage"];
            /**
             * Format: int32
             * @description Progress within the current stage, when the stage reports it.
             */
            progressPercent: number | null;
            errorMessage: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description One SSE `data:` payload on `GET /events`. */
        UserEvent: components["schemas"]["FilesSnapshotEvent"] | components["schemas"]["FileUpdatedEvent"];
        FilesSnapshotEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "files.snapshot";
            /** @description Every file still uploading or processing. */
            files: components["schemas"]["FileState"][];
        };
        FileUpdatedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file.updated";
            file: components["schemas"]["FileState"];
        };
        /** @description Palette token name, not a hex value. */
        CollectionColor: string;
        Collection: {
            id: components["schemas"]["Id"];
            name: string;
            description: string | null;
            color: components["schemas"]["CollectionColor"] | null;
            parentId: components["schemas"]["Id"] | null;
            /** Format: int32 */
            fileCount: number;
            /** Format: int32 */
            childCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateCollectionRequest: {
            name: string;
            description?: string;
            color?: components["schemas"]["CollectionColor"];
            parentId?: components["schemas"]["Id"];
        };
        UpdateCollectionRequest: {
            name?: string;
            description?: string | null;
            color?: components["schemas"]["CollectionColor"] | null;
            /** @description `null` moves the collection to the top level. */
            parentId?: components["schemas"]["Id"] | null;
        };
        AddCollectionFilesRequest: {
            fileIds: components["schemas"]["Id"][];
        };
        DeleteCollectionResult: {
            /** Format: int32 */
            deletedCollections: number;
            /** Format: int32 */
            deletedFiles: number;
        };
        CollectionPage: {
            items: components["schemas"]["Collection"][];
            nextCursor: string | null;
        };
        CollectionItem: components["schemas"]["CollectionItemCollection"] | components["schemas"]["CollectionItemFile"];
        CollectionItemCollection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "collection";
            collection: components["schemas"]["Collection"];
        };
        CollectionItemFile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "file";
            file: components["schemas"]["File"];
            /** Format: date-time */
            addedAt: string;
        };
        CollectionItemPage: {
            items: components["schemas"]["CollectionItem"][];
            nextCursor: string | null;
        };
        SearchRequest: {
            query: string;
            fileIds?: components["schemas"]["Id"][];
            collectionId?: components["schemas"]["Id"];
            types?: components["schemas"]["FileType"][];
            /**
             * Format: int32
             * @default 10
             */
            limit: number;
            tuning?: components["schemas"]["SearchTuning"];
        };
        /**
         * @description Retrieval knobs; omitted fields keep the server defaults. Text and image
         *     matches are fused by weighted reciprocal rank, so the weights set how much
         *     each modality's ranking counts, not a scale on raw similarities.
         */
        SearchTuning: {
            /**
             * @description Transcripts, scene descriptions and on-screen text. Not 0 together with imageWeight.
             * @default 0.5
             */
            textWeight: number;
            /**
             * @description Visual similarity of frames and images.
             * @default 0.5
             */
            imageWeight: number;
            /**
             * @description Minimum similarity per modality; applies only with dynamicRetrieval.
             * @default 0.2
             */
            threshold: number;
            /**
             * @description Consider five times `limit` candidates per modality and drop those under `threshold`.
             * @default true
             */
            dynamicRetrieval: boolean;
            /**
             * @description Blend the query with its key phrases before matching text.
             * @default true
             */
            queryExpansion: boolean;
        };
        SearchResults: {
            items: components["schemas"]["SearchHit"][];
        };
        VisualDescription: {
            summary: string | null;
            objects: string[];
            setting: string | null;
            style: string | null;
            colors: string[];
        };
        SearchHit: {
            fileId: components["schemas"]["Id"];
            fileName: string;
            fileType: components["schemas"]["FileType"];
            sceneId: components["schemas"]["Id"] | null;
            /** Format: int32 */
            sceneNumber: number | null;
            /** @description Rank-fused relevance; 1 means ranked first by every searched modality. */
            score: number;
            startSeconds: number | null;
            endSeconds: number | null;
            /** @description Matched transcript or text excerpt. */
            snippet: string | null;
            /** Format: uri */
            thumbnailUrl: string | null;
            /** Format: uri */
            fileUrl: string | null;
            /** Format: uri */
            youtubeUrl: string | null;
            visual: components["schemas"]["VisualDescription"] | null;
        };
        Conversation: {
            id: components["schemas"]["Id"];
            title: string | null;
            fileId: components["schemas"]["Id"] | null;
            collectionId: components["schemas"]["Id"] | null;
            /** Format: int32 */
            messageCount: number;
            lastMessagePreview: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateConversationRequest: {
            fileId?: components["schemas"]["Id"];
            collectionId?: components["schemas"]["Id"];
        };
        ConversationPage: {
            items: components["schemas"]["Conversation"][];
            nextCursor: string | null;
        };
        Message: {
            id: components["schemas"]["Id"];
            /** @enum {string} */
            role: "USER" | "ASSISTANT";
            content: string;
            hits: components["schemas"]["SearchHit"][];
            fileIds: components["schemas"]["Id"][];
            toolsUsed: string[];
            /** Format: date-time */
            createdAt: string;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            nextCursor: string | null;
        };
        SendMessageRequest: {
            content: string;
            /** @description Narrow retrieval for this message only. */
            fileIds?: components["schemas"]["Id"][];
        };
        Greeting: {
            greeting: string;
        };
        /** @description One SSE `data:` payload on `POST /conversations/{conversationId}/messages`. */
        ChatStreamEvent: components["schemas"]["ChatStepEvent"] | components["schemas"]["ChatToolEvent"] | components["schemas"]["ChatResultsEvent"] | components["schemas"]["ChatDeltaEvent"] | components["schemas"]["ChatDoneEvent"] | components["schemas"]["ChatErrorEvent"];
        /** @description Progress of a named pipeline step. */
        ChatStepEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
            step: string;
            label: string;
            /** @enum {string} */
            status: "STARTED" | "DONE" | "FAILED";
            error: string | null;
            errorCode: string | null;
        };
        ChatToolEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool";
            tool: string;
            /** @enum {string} */
            status: "STARTED" | "DONE";
            /** @description Set on STARTED. */
            arguments: Record<string, never> | null;
            /**
             * Format: int32
             * @description Set on DONE.
             */
            resultCount: number | null;
        };
        ChatResultsEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "results";
            /** @enum {string} */
            kind: "SEARCH" | "SCENE_THUMBNAILS";
            hits: components["schemas"]["SearchHit"][];
        };
        /** @description Assistant text to append. */
        ChatDeltaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
            text: string;
        };
        ChatDoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            messageId: components["schemas"]["Id"];
            toolsUsed: string[];
            /** Format: int32 */
            resultCount: number;
        };
        ChatErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            code: string;
            message: string;
        };
        Money: {
            /**
             * Format: int64
             * @description Minor units (cents, paise).
             */
            amountMinor: number;
            /** @description ISO 4217 code. */
            currency: string;
        };
        Plan: {
            id: components["schemas"]["Id"];
            name: string;
            description: string | null;
            type: components["schemas"]["PlanType"];
            interval: components["schemas"]["BillingInterval"];
            price: components["schemas"]["Money"];
            /** @description Limit per metric; 0 means unlimited. */
            limits: {
                [key: string]: number;
            };
            features: string[];
            /**
             * @description Relative to the caller's plan; `null` when anonymous.
             * @enum {string|null}
             */
            comparison: "CURRENT" | "UPGRADE" | "DOWNGRADE" | null;
        };
        PlanList: {
            items: components["schemas"]["Plan"][];
        };
        Subscription: {
            id: components["schemas"]["Id"];
            plan: components["schemas"]["Plan"];
            status: components["schemas"]["SubscriptionStatus"];
            /** Format: date-time */
            currentPeriodStart: string;
            /** Format: date-time */
            currentPeriodEnd: string;
            cancelAtPeriodEnd: boolean;
            /** Format: date-time */
            canceledAt: string | null;
            /** Format: date-time */
            trialEndsAt: string | null;
            scheduledChange: components["schemas"]["ScheduledChange"] | null;
            /** Format: date-time */
            nextPaymentAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ScheduledChange: {
            /** @enum {string} */
            kind: "DOWNGRADE" | "CANCEL_TO_FREE";
            planId: components["schemas"]["Id"];
            /** Format: date-time */
            effectiveAt: string;
        };
        ChangePlanRequest: {
            planId: components["schemas"]["Id"];
        };
        ChangePlanResult: {
            subscription: components["schemas"]["Subscription"];
            /**
             * Format: uri
             * @description When set, redirect the user here to pay.
             */
            checkoutUrl: string | null;
        };
        CancelSubscriptionRequest: {
            /**
             * @description Cancel now instead of at period end.
             * @default false
             */
            immediate: boolean;
        };
        QuotaUsage: {
            metric: components["schemas"]["UsageMetric"];
            /** Format: int64 */
            used: number;
            /**
             * Format: int64
             * @description 0 means unlimited.
             */
            limit: number;
            /** Format: date-time */
            resetAt: string | null;
        };
        StorageUsage: {
            /** Format: int64 */
            usedBytes: number;
            /**
             * Format: int64
             * @description 0 means unlimited.
             */
            limitBytes: number;
            /** Format: int32 */
            fileCount: number;
        };
        Usage: {
            planType: components["schemas"]["PlanType"];
            quotas: components["schemas"]["QuotaUsage"][];
            storage: components["schemas"]["StorageUsage"];
        };
    };
    responses: {
        /** @description Invalid request (`validation_failed`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://docs.ragspace.app/errors/validation_failed",
                 *       "title": "Validation failed",
                 *       "status": 400,
                 *       "detail": "One or more fields are invalid.",
                 *       "code": "validation_failed",
                 *       "correlationId": "3f1c2a9e-8b7d-4c1e-9f0a-2b6d5e4c3a21",
                 *       "errors": [
                 *         {
                 *           "field": "name",
                 *           "message": "must not be empty"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid session, or bad credentials (`unauthenticated`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Request refused (`forbidden`): failed `Origin` check, or the operation
         *     needs a fresher session.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource does not exist or is not the caller's (`not_found`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Current state does not allow the request (`conflict`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Plan limit reached (`quota_exceeded`); upgrade to continue. */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://docs.ragspace.app/errors/quota_exceeded",
                 *       "title": "Quota exceeded",
                 *       "status": 402,
                 *       "detail": "Your plan allows 3 YouTube imports per month.",
                 *       "code": "quota_exceeded",
                 *       "correlationId": "3f1c2a9e-8b7d-4c1e-9f0a-2b6d5e4c3a21",
                 *       "metric": "YOUTUBE_VIDEOS",
                 *       "used": 3,
                 *       "limit": 3
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limited (`rate_limited`). */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "RateLimit-Reset": components["headers"]["RateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Unexpected failure (`internal`), a dependency is down
         *     (`upstream_unavailable`, 503) or timed out (`upstream_timeout`, 504).
         */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Limit: number;
        /** @description Opaque `nextCursor` from the previous page. */
        Cursor: string;
        /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
        IdempotencyKey: string;
        FileId: components["schemas"]["Id"];
        CollectionId: components["schemas"]["Id"];
        ConversationId: components["schemas"]["Id"];
        OAuthProvider: "google";
    };
    requestBodies: never;
    headers: {
        /** @description Sets or clears the httpOnly session cookie. */
        SetSessionCookie: string;
        /** @description URL of the created or target resource. */
        Location: string;
        /** @description Seconds until the client may retry. */
        RetryAfter: number;
        /** @description Requests allowed in the current window. */
        RateLimitLimit: number;
        /** @description Requests left in the current window. */
        RateLimitRemaining: number;
        /** @description Seconds until the window resets. */
        RateLimitReset: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Account created and session started. */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Session started. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    startOAuth: {
        parameters: {
            query?: {
                /** @description Same-origin path to land on after sign-in. */
                redirectTo?: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the provider's consent screen. */
            302: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    completeOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session started; redirect to `redirectTo`. */
            302: {
                headers: {
                    Location: components["headers"]["Location"];
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload with presigned part URLs. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description The file, now queued for processing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    abortUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload aborted, file removed, quota released. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listFiles: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque `nextCursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
                type?: components["schemas"]["FileType"];
                uploadStatus?: components["schemas"]["UploadStatus"];
                processingStatus?: components["schemas"]["ProcessingStatus"];
                processingStage?: components["schemas"]["ProcessingStage"];
                /** @description Only files directly in this collection. */
                collectionId?: components["schemas"]["Id"];
                /** @description Only these files. */
                ids?: components["schemas"]["Id"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of files, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    importFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportFileRequest"];
            };
        };
        responses: {
            /** @description The new file, queued for processing. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. Derived data is purged asynchronously. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    updateFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFileRequest"];
            };
        };
        responses: {
            /** @description Updated file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    reprocessFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["UserEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listCollections: {
        parameters: {
            query?: {
                /**
                 * @description Omit for every collection (flat). `root` for top-level only. A
                 *     collection id for its direct children.
                 */
                parentId?: components["schemas"]["Id"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque `nextCursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of collections, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteCollection: {
        parameters: {
            query?: {
                /** @description Also delete every file in the collection tree. */
                deleteFiles?: boolean;
            };
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCollectionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    updateCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollectionRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listCollectionItems: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque `nextCursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    addCollectionFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollectionFilesRequest"];
            };
        };
        responses: {
            /** @description Updated collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    removeCollectionFiles: {
        parameters: {
            query: {
                ids: components["schemas"]["Id"][];
            };
            header?: never;
            path: {
                collectionId: components["parameters"]["CollectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Best matches first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listConversations: {
        parameters: {
            query?: {
                fileId?: components["schemas"]["Id"];
                collectionId?: components["schemas"]["Id"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque `nextCursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recently active first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque `nextCursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Reply stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatStreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getGreeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Greeting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active plans, cheapest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanList"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    changePlan: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated UUID; retries with the same key within 24h return the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePlanRequest"];
            };
        };
        responses: {
            /** @description Result of the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePlanResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    pauseSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    resumeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    cancelScheduledChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-Signature"?: string;
                "X-Razorpay-Signature"?: string;
            };
            path: {
                provider: "lemon-squeezy" | "razorpay";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Processed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["ServerError"];
        };
    };
}
