"""
Codegen script: compiles JSON Schema files in contracts/ into Pydantic v2 models.
Run: python scripts/generate.py  (called by CI and pre-build hooks)

Tool: datamodel-code-generator (pip install datamodel-code-generator)
Output: ragspace_shared/generated/  — DO NOT EDIT these files by hand.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]          # repo root
CONTRACTS = ROOT / "contracts"
OUT = Path(__file__).resolve().parents[1] / "ragspace_shared" / "generated"

BANNER = (
    "# =============================================================\n"
    "# DO NOT EDIT — generated from contracts/ by scripts/generate.py\n"
    "# Run `python scripts/generate.py` in packages/shared-py to regenerate.\n"
    "# =============================================================\n\n"
)

ENTRIES = [
    # (input_path, output_path, module_name)
    (CONTRACTS / "schemas" / "AuthUser.json",           OUT / "auth_user.py",            "AuthUser"),
    (CONTRACTS / "schemas" / "AuthSession.json",        OUT / "auth_session.py",         "AuthSession"),
    (CONTRACTS / "schemas" / "UploadedFile.json",       OUT / "uploaded_file.py",        "UploadedFile"),
    (CONTRACTS / "schemas" / "Scene.json",              OUT / "scene.py",                "Scene"),
    (CONTRACTS / "schemas" / "UsageCheckResult.json",   OUT / "usage_check_result.py",   "UsageCheckResult"),
    (CONTRACTS / "schemas" / "PlanValidationResult.json",OUT / "plan_validation_result.py","PlanValidationResult"),
    # enums/ and events/ are generated by custom helpers below (not datamodel-code-generator)
]


def to_enum_key(value: str) -> str:
    """Convert a dotted routing key to a valid Python enum identifier.

    'file.upload.started'        → UPLOAD_STARTED   (3+ segments: strip first)
    'file.deleted'               → FILE_DELETED      (2 segments: keep all)
    'VIDEO'                      → VIDEO             (1 segment: sanitize+upper)
    'file.scene.detection.started' → SCENE_DETECTION_STARTED  (4 segments: strip first)
    """
    parts = value.split(".")
    if len(parts) == 1:
        return re.sub(r"[^a-zA-Z0-9_]", "_", value).upper()
    relevant = parts[1:] if len(parts) > 2 else parts
    return "_".join(relevant).upper()


def generate_enums() -> None:
    enums_contracts = CONTRACTS / "enums"
    out_dir = OUT / "enums"
    out_dir.mkdir(parents=True, exist_ok=True)

    blocks: list[str] = [BANNER, "from enum import Enum\n\n"]
    for json_file in sorted(enums_contracts.glob("*.json")):
        schema = json.loads(json_file.read_text(encoding="utf-8"))
        name = schema.get("title") or json_file.stem
        values = schema.get("enum", [])
        lines = [f"class {name}(str, Enum):"]
        for v in values:
            lines.append(f'    {to_enum_key(v)} = "{v}"')
        blocks.append("\n".join(lines) + "\n\n\n")

    out_file = out_dir / "__init__.py"
    out_file.write_text("".join(blocks).rstrip() + "\n", encoding="utf-8")
    print(f"  ✓ {enums_contracts.relative_to(ROOT)} → {out_file.relative_to(ROOT)}")


def run_codegen(input_path: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", str(input_path),
        "--input-file-type", "jsonschema",
        "--output", str(output_path),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--field-constraints",
        "--use-annotated",
        "--snake-case-field",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR generating {input_path}:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    print(f"  ✓ {input_path.relative_to(ROOT)} → {output_path.relative_to(ROOT)}")


def prepend_banners(base: Path) -> None:
    for py_file in base.rglob("*.py"):
        if py_file.name == "__init__.py":
            continue
        content = py_file.read_text(encoding="utf-8")
        if "DO NOT EDIT" not in content:
            py_file.write_text(BANNER + content, encoding="utf-8")


if __name__ == "__main__":
    print("Generating Python models from JSON Schema...")
    OUT.mkdir(parents=True, exist_ok=True)

    for inp, out, _ in ENTRIES:
        run_codegen(inp, out)

    generate_enums()

    prepend_banners(OUT)
    print("Done.")
